---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  jobName: node-exporter
  targetEndpoints:
    - targets:
        - "192.168.100.31:9100"
        - "192.168.100.32:9100"
        - "192.168.100.33:9100"
      labels:
        job: node-exporter

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: nginx-exporter
  namespace: monitoring
spec:
  jobName: nginx-exporter
  targetEndpoints:
    - targets:
        - "192.168.100.31:9113"
      labels:
        job: nginx-exporter
        instance: traffic-proxy-01

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: postgres-exporter
  namespace: monitoring
spec:
  jobName: postgres-exporter
  targetEndpoints:
    - targets:
        - "192.168.100.33:9187"
      labels:
        job: postgres-exporter
        instance: postgres-01
