apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trilium-notes
  namespace: argocd
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/nobleman97/homelab.git
    path: k8s/charts/trilium-notes
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../values/trilium-notes/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      