global:
  domain: argo.osose.xyz

configs:
  params:
    server.insecure: true
    
server:
  ingress:
    enabled: false  # Cloudlare --> Tunnel --> ArgoCD
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    extraTLS:
      - secretName: argocd-tls
        hosts:
          - argo.osose.xyz



# helm install my-argo-cd argo/argo-cd --version 9.5.4 -f values.yaml -n argocd
