global:
  domain: argo.osose.xyz

configs:
  params:
    server.insecure: true

  cm:
    oidc.config: |
      name: authentik
      issuer: https://auth.osose.xyz/application/o/argocd/
      clientID: oLyMdhljwzKAJP7ySnVO0XvB5VaXYrP4ROEAafNz
      clientSecret: $oidc.authentik.clientSecret
      requestedScopes:
        - openid
        - profile
        - email
        - groups

  rbac:
    policy.csv: |
      g, argocd-admins, role:admin
    policy.default: role:readonly
    
server:
  ingress:
    enabled: false  # Cloudlare --> Tunnel --> ArgoCD
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    extraTLS:
      - secretName: argocd-tls
        hosts:
          - argo.osose.xyz



# helm install argocd argo/argo-cd --version 9.5.4 -f values.yaml -n argocd
